FROM node:20

RUN yarn set version 4.5.0

WORKDIR /app

EXPOSE 8545

COPY package.json .
COPY yarn.lock .
COPY .yarnrc.yml .
COPY .yarn .

COPY packages/blockchain/package.json ./packages/blockchain/ 

RUN yarn workspaces focus @nft-open-marketplace/blockchain

WORKDIR /app/packages/blockchain
