version: "3.8"

services:
  blockchain:
    build:
      context: .
      dockerfile: ./Dockerfile.node
    ports:
      - "8545:8545"
    volumes:
      - ./packages/blockchain:/app/packages/blockchain
    networks:
      - hardhat-net
    command: "yarn run node"
    env_file:
      - .env

  deploy-blockchain:
    build:
      context: .
      dockerfile: ./Dockerfile.node
    depends_on:
      - blockchain
    networks:
      - hardhat-net
    volumes:
      - ./packages/blockchain:/app/packages/blockchain
      - ./shared:/app/shared
    command: "yarn run deploy:local"
    env_file:
      - .env

  ui:
    build:
      context: .
      dockerfile: ./Dockerfile.ui
    ports:
      - "3000:3000"
    volumes:
      - ./packages/ui:/app/packages/ui
      - ./shared:/app/shared
    depends_on:
      - deploy-blockchain
    command: "yarn run dev"
    env_file:
      - .env

networks:
  hardhat-net:
    driver: bridge
