FROM golang:1.23

WORKDIR /app

RUN go install github.com/go-delve/delve/cmd/dlv@latest

RUN go install github.com/air-verse/air@latest

COPY packages/backend/go.mod ./packages/backend/
COPY packages/backend/go.sum ./packages/backend/

WORKDIR /app/packages/backend

RUN go mod tidy

EXPOSE 8080 40000
