FROM node:18

WORKDIR /app

COPY yarn.lock .
COPY package.json .

COPY packages/pnft-market-etherium/package.json ./packages/pnft-market-etherium/
# COPY packages/pnft-market-etherium/hardhat.config.ts ./packages/pnft-market-etherium/

RUN yarn install

WORKDIR /app/packages/pnft-market-etherium

RUN yarn install
