version: "3.8"

services:
  blockchain:
    build:
      context: .
      dockerfile: ./Dockerfile.node
    ports:
      - "8545:8545"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - hardhat-net
    env_file:
      - .env

  deploy-blockchain:
    build:
      context: .
      dockerfile: ./Dockerfile.deploy
    depends_on:
      - blockchain
    networks:
      - hardhat-net
    volumes:
      - ./packages/pnft-market-etherium:/app/packages/pnft-market-etherium
    command: "yarn run deploy:local"
    env_file:
      - .env

  ui:
    build:
      context: .
      dockerfile: ./Dockerfile.ui
    ports:
      - "3000:3000"
    volumes:
      - ./packages/pnft-market-ui:/app/packages/pnft-market-ui
      - /app/node_modules
    depends_on:
      - deploy-blockchain
    command: "npm run dev"
    env_file:
      - .env

networks:
  hardhat-net:
    driver: bridge
