FROM node:18

WORKDIR /app

COPY yarn.lock .
COPY package.json .

COPY packages/pnft-market-ui/package.json ./packages/pnft-market-ui/

RUN yarn install

WORKDIR /app/packages/pnft-market-ui

RUN yarn install

EXPOSE 3000
