import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header.component";
import Footer from "@/components/footer/footer.component";
import MetaMaskProviderWrapper from "@/providers/metamask.provider";
import { EthereumProvider } from "@/providers/etherium.provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MetaMaskProviderWrapper>
        <EthereumProvider>
          <body className={inter.className}>
            <Header />
            {children}
            <Footer />
          </body>
        </EthereumProvider>
      </MetaMaskProviderWrapper>
    </html>
  );
}
