/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openMarketplaceSol from "./OpenMarketplace.sol";
export type { openMarketplaceSol };
export type { OpenMarketplaceNFT } from "./OpenMarketplaceNFT";
